name: Chrome headless

on: push

jobs:
  chrome-headless:
    runs-on: ubuntu-latest
    # https://github.com/cypress-io/cypress-docker-images
    container: cypress/browsers:node12.18.3-chrome87-ff82
    environment: test0
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Headless Chrome
        uses: cypress-io/github-action@v2
        timeout-minutes: 10
        with:
          build: npm run release-build
          start: node server.js
          browser: chrome
          headless: true
          record: true
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.dashboardRecordKey }}
