name: Chrome Headless Manual

on: 
  workflow_dispatch:
  push:
    branches:
      - unstable

jobs:
  chrome-headless:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node14.16.0-chrome89-ff86
    environment: test0
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 14.19.3
      
      - name: Setup ORSE SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.ORSE_DEPLOY_KEY }}

      - name: Add GitHub to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Install dependencies
        run: npm install
      
      - name: Headless Chrome
        uses: cypress-io/github-action@v6
        with:
          build: npm run release-build
          start: node server.js
          browser: chrome
          record: true
          install: false
        env:
          PORT: 3000
          CYPRESS_RECORD_KEY: ${{ secrets.dashboardRecordKey }} 